[project]
name = "wireless-telem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = []

[tool.uv.workspace]
members = ["services/broker",
    "./services/can-reader",
    "./services/can-simulator",
    "./services/rf-sender",
    "./services/sd-logger"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

