[project]
name = "wireless-telem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = [
    "can-reader",
    "sd-logger",
    "rf-sender",
    "shared",
    "broker",
    "can-simulator",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

