[project]
name = "wireless-telem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asammdf>=8.8.9",
    "pyserial>=3.5",
    "python-can>=4.6.1",
    "pyzmq>=27.1.0",
]

[tool.uv.workspace]
members = [
    "can-reader",
    "mdf4-logger",
    "rf-sender",
    "shared",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

